        # Exquisite Colors
        colors:
          primary:
            background: '#070219'
            foreground: '#c0caf5'

          normal:
            black:   '#626483'
            red:     '#fb007a'
            green:   '#a6e22e'
            yellow:  '#f3e430'
            blue:    '#58AFC2'
            magenta: '#583794'
            cyan:    '#926BCA'
            white:   '#d9d9d9'

          bright:
            black:   '#626483'
            red:     '#fb007a'
            green:   '#a6e22e'
            yellow:  '#f3e430'
            blue:    '#58AFC2'
            magenta: '#472575'
            cyan:    '#926BCA'
            white:   '#f1f1f1'
          
          cursor:
            cursor: '#fb007a'
            text: '#070219'
