---
- name: Zsh | Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: true
  become: true
  when: machine_os == 'debian'

- name: Zsh | Install zsh
  community.general.pacman:
    name: zsh
    state: present
  become: true
  when: machine_os == 'archlinux'

- name: Zsh | Install zsh
  ansible.builtin.dnf:
    name: zsh
    state: present
  become: true
  when: machine_os == 'redhat'

- name: Zsh | Remove existing .zshrc if there is
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.zshrc"
    state: absent

- name: Zsh | Link .zshrc
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/dotfiles/.zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    state: link

- name: Zsh | Remove existing ~/.config/zsh if there is
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/zsh"
    state: absent

# - name: Zsh | Copy zhistory and zcompdump
#   ansible.builtin.file:
#     src: "{{ ansible_user_dir }}/dotfiles/config/zsh"
#     dest: "{{ ansible_user_dir }}/.config/zsh"
#     owner: "{{ host_user }}"
#     state: link

# - name: Zsh | Copy zhistory and zcompdump
#   ansible.builtin.copy:
#     src: "{{ ansible_user_dir }}/dotfiles/config/zsh"
#     dest: "{{ ansible_user_dir }}/.config/zsh"
#     owner: "{{ host_user }}"
#     mode: "0644"

- name: Zsh | Make zsh the default shell
  become: true
  ansible.builtin.user:
    name: "{{ host_user }}" # defined in pre-tasks in main playbook
    shell: /usr/bin/zsh
