- name: Essentials Arch | Install essential packages
  community.general.pacman:
    name:
      - sudo
      - git
      - fd
      - ripgrep
      - curl
      - fzf
      - cmake
      - gcc
      - vim
      # - pkg-config
      - libtool
      - unzip
      - zip
      - gzip
      - lsd
      - gnupg # gpg
      - pass
      - yq
      - jq
      - open-iscsi
      - tar
      - wget
      - imagemagick
      - bat
      - redshift
      - copyq
      # - aria2c (in aur)
      # - qemu-guest-agent
    state: present
  become: true
