- name: Essentials Debian | Install essential packages
  ansible.builtin.apt:
    name:
      - git
      - fd-find # NOTE: binary is 'fdfind' in debian, might need to mv it to 'fd' for convenience
      - ripgrep
      - curl
      - fzf
      - cmake
      - gcc
      - vim
      # - pkg-config
      - libtool
      - unzip
      - zip
      - gzip
      - lsd
      - gnupg
      - pass
      - yq
      - jq
      - open-iscsi
      - tar
      - wget
      # - aria2c
      - qemu-guest-agent
    state: present
    update_cache: true
  become: true
