- name: Essentials | Configure install packages for Archlinux
  ansible.builtin.import_tasks: archlinux.yml
  when: machine_os == 'archlinux'

- name: Essentials | Configure install packages for Debian
  ansible.builtin.import_tasks: debian.yml
  when: machine_os == 'debian'

- name: Essentials | Configure install packages for Redhat (Fedora)
  ansible.builtin.import_tasks: redhat.yml
  when: machine_os == 'redhat'

- name: Downloads | Create proper directory structure
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/downloads"
    state: directory
    mode: "0755"

- name: Personal | Create proper directory structure
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/personal"
    state: directory
    mode: "0755"

- name: Work | Create proper directory structure
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/work"
    state: directory
    mode: "0755"

- name: Config | Create proper directory structure
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    mode: "0755"
