- name: Essentials RedHat | Install essential packages
  ansible.builtin.dnf:
    name:
      - sudo
      - git
      - fd-find
      - ripgrep
      - curl
      - cmake
      - gcc
      - vim
      - libtool
      - unzip
      - zip
      - gzip
      - lsd
      - gnupg
      - pass
      - pass-extension-otp
      - yq
      - jq
      - open-iscsi
      - tar
      - wget
      # - aria2c
      - qemu-guest-agent
      - fzf
      - rsync
      - cryptsetup
      - cronie
      - openssh-server
      - delta
      - bat
      - tcpdump
      - psutils
      - moreutils
      - less
      - cargo
      - acpi
      # - oha
      # - websocat
    state: present
    update_cache: true
  become: true
