# called if changed=True on config change on timesyncd.conf or ntp.conf
- name: Timezone/NTP | Restart timesyncd.service
  ansible.builtin.systemd_service:
    name: systemd-timesyncd.service
    state: restarted
