---
- name: Discord | install rpm fusion repositories if not yet installed
  ansible.builtin.dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
    state: present
    disable_gpg_check: false
  become: true

- name: Discord | install discord via dnf
  ansible.builtin.dnf:
    name: discord
    state: present
  become: true
