# - name: Go | Install Go for Debian (Golang)
#   ansible.builtin.apt:
#     name: golang
#     state: present
#   become: true

- name: Go | Get go tarball
  ansible.builtin.get_url:
    url: https://go.dev/dl/go1.23.4.linux-amd64.tar.gz
    # url: https://go.dev/dl/go@latest.linux-amd64.tar.gz
    dest: "{{ ansible_user_dir }}/downloads/go1.23.4.linux-amd64.tar.gz"
    checksum: sha256:6924efde5de86fe277676e929dc9917d466efa02fb934197bc2eba35d5680971

- name: Go | Ensure no previous installation
  ansible.builtin.file:
    path: /usr/local/go
    state: absent

- name: Go | Install go
  ansible.builtin.unarchive:
    src: "{{ ansible_user_dir }}/downloads/go1.23.4.linux-amd64.tar.gz"
    dest: /usr/local
  become: true

# no need to add /usr/local/go to PATH since it is already in our .zshrc/.bashrc

- name: Go | Confirm go installation
  ansible.builtin.shell: "source {{ ansible_user_dir }}/.zshrc && go version"
  # ansible.builtin.shell: "source {{ ansible_env.HOME }}/.zshrc"
>>>>>>> f22a68d (chore: fix errors)
