---
# - name: Go | Install Go for Debian (Golang)
#   ansible.builtin.apt:
#     name: golang
#     state: present
#   become: true

- name: Go | Get latest Go version
  ansible.builtin.uri:
    url: https://go.dev/VERSION?m=text
    return_content: yes
  register: go_latest_version

- name: Go | Set Go version fact
  ansible.builtin.set_fact:
    go_version: "{{ go_latest_version.content.split('\n')[0] }}"

- name: Go | Get go tarball
  ansible.builtin.get_url:
    url: "https://go.dev/dl/{{ go_version }}.linux-amd64.tar.gz"
    dest: "{{ ansible_user_dir }}/Downloads/{{ go_version }}.linux-amd64.tar.gz"
    checksum: "sha256:{{ lookup('url', 'https://go.dev/dl/{{ go_version }}.linux-amd64.tar.gz.sha256') }}"

- name: Go | Ensure no previous installation
  ansible.builtin.file:
    path: /usr/local/go
    state: absent

- name: Go | Install go
  ansible.builtin.unarchive:
    src: "{{ ansible_user_dir }}/Downloads/{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local
  become: true

# no need to add /usr/local/go to PATH since it is already in our .zshrc/.bashrc

- name: Go | Confirm go installation
  ansible.builtin.shell: "source {{ ansible_user_dir }}/.zshrc && go version"
  # ansible.builtin.shell: "source {{ ansible_env.HOME }}/.zshrc"
