- name: Go | Configure install packages for Archlinux
  ansible.builtin.import_tasks: archlinux.yml
  when: machine_os == 'archlinux'

- name: Go | Configure install packages for Debian
  ansible.builtin.import_tasks: debian.yml
  when: machine_os == 'debian'

- name: Go | Configure install packages for RedHat
  ansible.builtin.import_tasks: debian.yml
  when: machine_os == 'redhat'
