---
- name: Iosevka | Ensure curl and unzip are installed
  ansible.builtin.package:
    name:
      - curl
      - unzip
    state: present
  become: true

- name: Iosevka | Create fonts directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: directory
    mode: '0755'
  become: true

- name: Iosevka | Get latest Iosevka release
  ansible.builtin.uri:
    url: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest
    return_content: yes
  register: iosevka_latest_release

- name: Iosevka | Set Iosevka version fact
  ansible.builtin.set_fact:
    iosevka_version: "{{ iosevka_latest_release.json.tag_name }}"

- name: Iosevka | Download Iosevka Term Nerd Font archive
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ iosevka_version }}/IosevkaTerm.tar.xz"
    dest: "/tmp/IosevkaTerm.tar.xz"
    mode: '0644'
    force: false
  become: true
  register: download_result

- name: Iosevka | Unpack Iosevka Term Nerd Font
  ansible.builtin.unarchive:
    src: "/tmp/IosevkaTerm.tar.xz"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"
    extra_opts: ["-o"]
    remote_src: true
  become: true
  when: download_result is changed
  notify: Refresh font cache

- name: Iosevka | Remove downloaded archive
  ansible.builtin.file:
    path: "/tmp/IosevkaTerm.tar.xz"
    state: absent
  become: true
  when: download_result is changed
