---
- name: Neovim | Ensure old neovim from repository is uninstalled
  community.general.pacman:
    name: neovim
    state: absent

- name: Neovim | Make sure 'dependencies' are installed
  community.general.pacman:
    name:
      # make sure 'dependencies' are installed
      - gcc
      - make
      - git
      - ripgrep
      - fd
      - unzip
      - lua5.4
      - luarocks
      - lua5.1
    state: present
    extra_args: --noconfirm
  become: true

- name: Neovim | Install latest stable Neovim version via pacman
  community.general.pacman:
    name: neovim
    state: present
    extra_args: --noconfirm
  become: true

- name: Neovim | Copy own nvim configs
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/dotfiles/nvim"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
