---
- name: Neovim | Ensure old neovim from repository is uninstalled
  ansible.builtin.apt:
    name: neovim
    state: absent

- name: Neovim | Make sure 'dependencies' are installed
  ansible.builtin.apt:
    name:
      - gcc
      - make
      - git
      - ripgrep
      - fd-find
      - unzip
      - curl
      # - xclip
      - libfuse2
      - lua5.4
      - luarocks
      - lua5.1
    state: present
  become: true

- name: Neovim | Create /opt/nvim directory as download directory
  ansible.builtin.file:
    path: "/opt/nvim"
    owner: root
    group: root
    mode: "0755" # drwxr-x-r-x
    state: directory
  become: true

- name: Neovim | Get/Install nvim.appimage
  ansible.builtin.get_url:
    url: "{{ neovim_appimage_url }}"
    dest: "/opt/nvim/nvim.appimage"
    mode: "0555" # -r-x-r-x-r-x
  become: true

- name: Neovim | Copy nvim.appimage bin to /usr/local/bin/nvim for global PATH
  ansible.builtin.copy:
    src: "/opt/nvim/nvim.appimage"
    dest: "/usr/local/bin/nvim" # or "/usr/bin/nvim" directly?
    owner: root
    group: root
    mode: "0755" # -rwx-r-x-r-x
    remote_src: true
  become: true

- name: Neovim | Copy own nvim configs
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/dotfiles/nvim"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
