---
- name: Neovim | Ensure old neovim from repository is uninstalled
  ansible.builtin.dnf:
    name: neovim
    state: absent
  become: true

- name: Neovim | Make sure dependencies are installed
  ansible.builtin.dnf:
    name:
      # make sure 'dependencies' are installed
      - gcc
      - make
      - git
      - ripgrep
      - fd-find
      - unzip
      - lua
      - luarocks
      - lua5.1
      - python3-pip
    state: present
  become: true

- name: Neovim | Install COPR dependencies
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present
  become: true

- name: Neovim | Enable agriffis/neovim-nightly COPR repository
  community.general.copr:
    name: agriffis/neovim-nightly
    state: enabled
  become: true
  register: copr_result
  changed_when: copr_result is changed

- name: Neovim | Clean and refresh DNF cache
  ansible.builtin.dnf:
    update_cache: true
  become: true

- name: Neovim | Install latest Neovim and Python support from COPR
  ansible.builtin.dnf:
    name:
      - neovim
      - python3-neovim
    state: present
    update_cache: true
  become: true

- name: Neovim | Copy own nvim configs
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/dotfiles/nvim"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link

- name: Neovim | Check nvim binary
  ansible.builtin.stat:
    path: "/usr/bin/nvim"
  register: nvim_binary
  check_mode: false

- name: Neovim | Suggest runner if copr install did not work
  ansible.builtin.debug:
    msg: "Neovim was not found. Use dotfiles/runner/neovim-nightly.sh to install neovim-nightly"
  when: not nvim_binary.stat.exists
