---
- name: Neovim | Ensure old neovim from repository is uninstalled
  ansible.builtin.dnf:
    name:
      - neovim
      - python3-neovim
    state: absent
  become: true

- name: Neovim | Make sure dependencies are installed
  ansible.builtin.dnf:
    name:
      # make sure 'dependencies' are installed
      - gcc
      - make
      - git
      - ripgrep
      - fd-find
      - unzip
      - lua
      - luarocks
      - lua5.1
      - python3-pip
    state: present
  become: true

- name: Neovim | Install neovim
  ansible.builtin.dnf:
    name:
      - neovim
    state: present
  become: true

- name: Neovim | Copy own nvim configs
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/dotfiles/nvim"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link

- name: Neovim | Check nvim binary
  ansible.builtin.stat:
    path: "/usr/bin/nvim"
  register: nvim_binary
  check_mode: false

- name: Neovim | Suggest runner if neovim fails to install (and if want latest version)
  ansible.builtin.debug:
    msg: "Neovim was not found. Use dotfiles/runner/neovim-nightly.sh to install neovim-nightly"
  when: not nvim_binary.stat.exists
