---
- name: Nerd Font | Install Jetbrains Mono Nerd Font (Arch)
  community.general.pacman:
    name:
      - ttf-jetbrains-mono
      - ttf-jetbrains-mono-nerd
    state: present
  become: true
  notify: Nerd Font | Refresh fc-cache list
