---
- name: Python | Install Python for Arch
  community.general.pacman:
    name:
      - python
      - python-pip
    state: present
  become: true
  when: machine_os == 'archlinux'

- name: Python | Install Python for Debian
  ansible.builtin.apt:
    name:
      - python3
      - python-pip
    state: present
  become: true
  when: machine_os == 'debian'

- name: Python | Install Python for Fedora
  ansible.builtin.apt:
    name:
      - python3
      - python-pip
    state: present
  become: true
  when: machine_os == 'redhat'
