- name: Development (Arch) | Install Go
  community.general.pacman:
    name: go
    state: present
  become: true

- name: Development (Arch) | Install JS/TS
  community.general.pacman:
    name:
      - nodejs
      - pnpm
      - npm
    state: present
  become: true

- name: Development (Arch) | Install nvm for JS/TS
  kewlfft.aur.aur:
    name: nvm
    state: present
  become: true

- name: Development (Arch) | Install Python
  community.general.pacman:
    name:
      - python
      - python-pip
      - python-pipx
    state: present
  become: true
