- name: Development (Debian) | Install Go
  ansible.builtin.apt:
    name: go
    state: present
  become: true

- name: Development (Debian) | Install JS/TS
  ansible.builtin.apt:
    name:
      - nodejs
      - pnpm
      - npm
    state: present
  become: true

- name: Development (Debian) | Install nvm for JS/TS
  kewlfft.aur.aur:
    name: nvm
    state: present
  become: true

- name: Development (Debian) | Install Python
  ansible.builtin.apt:
    name:
      - python
      - python-pip
      - python-pipx
    state: present
  become: true
