- name: SSH | Configure/Copy SSH keys
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: "0600"
  no_log: true
  loop_control:
    loop_var: ssh_key_item
  with_items: "{{ ssh_key | default({}) | dict2items }}"
  # register: ssh_k

# - name: DEBUG/SSH vals
#   ansible.builtin.debug:
#     var: ssh_k

