- name: SSH | Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ ssh_keys_path }}"
    state: directory
    mode: "0700"

- name: SSH | Configure SSH keys
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: "0600"
  no_log: true
  loop: "{{ ssh_keys | dict2items }}"
  loop_control:
    loop_var: ssh_key_item
