# install collections via: ansible-galaxy collection install -r requirements.yml
collections:
  - name: community.general
  # - name: kubernetes.core
  - name: kewlfft.aur # https://github.com/kewlfft/ansible-aur
