####################
#     REQUIRED:    #
####################
git_user_name: "ejsadiarin"
git_user_email:
# Development
wants_development: true
wants_java: true
wants_csharp_dotnet: true
#
#
####################
#     OPTIONAL:    #
####################
# OPENAI_KEY:
# OPENAI_API_KEY:

# k8s:
#   repo_version: "v1.26"
#
# helm:
#   repos:
#     - name: traefik
#       url: https://helm.traefik.io/traefik
#
# go:

# ssh_key:
#   id_ed25519:
#   id_ed25519.pub:
