- name: Development (Arch) | Install CSharp/Dotnet
  community.general.pacman:
    name:
      - dotnet-runtime
      - dotnet-sdk
      - aspnet-runtime
    state: present
  become: true
  when: machine_os == 'archlinux'

- name: Development (Debian) | Get deb packages
  ansible.builtin.shell: >
    wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb
  become: true
  when: machine_os == 'debian'

- name: Development (Debian) | Install CSharp/Dotnet
  ansible.builtin.apt:
    name:
      - dotnet-sdk-8.0
      - aspnetcore-runtime-8.0
    state: present
  become: true
  when: machine_os == 'debian'
