---
- name: Packet Tracer | detect fedora/redhat
  ansible.builtin.import_tasks: redhat.yml
  when: machine_os == 'redhat'

- name: Packet Tracer | detect archlinux
  ansible.builtin.import_tasks: archlinux.yml
  when: machine_os == 'archlinux'

- name: Packet Tracer | detect debian
  ansible.builtin.import_tasks: debian.yml
  when: machine_os == 'debian'
