---
- name: Packet Tracer | git clone packettracer-fedora script
  ansible.builtin.git:
    repo: "https://github.com/thiagoojack/packettracer-fedora.git"
    dest: "{{ ansible_env.HOME }}/personal/packettracer-fedora"

- name: Packet Tracer | wget latest packet tracer .deb package

- name: Packet Tracer | execute setup script on specified directory containing the .deb package

- name: Packet Tracer | edit /usr/share/applications/cisco-pt821.desktop
