---
- name: LazyDocker | Install LazyDocker via go install for debian
  ansible.builtin.shell: "go install github.com/jesseduffield/lazydocker@latest"
  when: machine_os == 'debian'

- name: LazyDocker | Install LazyDocker for archlinux
  # kewlfft.aur.aur:
  #   use: paru
  #   name: lazydocker
  community.general.pacman:
    name: lazydocker
    state: present
  become: true
  when: machine_os == 'archlinux'

- name: LazyDocker | Add LazyDocker repo via copr for redhat
  community.general.copr:
    host: copr.fedorainfracloud.org
    name: atim/lazydocker
    state: enabled
  become: true
  when: machine_os == 'redhat'

- name: LazyDocker | Install LazyDocker for redhat
  ansible.builtin.dnf:
    name: lazydocker
    state: present
  become: true
  when: machine_os == 'redhat'
