# Configure NTP Timezone Sync
- name: Timezone/NTP | Set local timezone # use 'UTC' maybe? eehhhhhhh
  community.general.timezone:
    name: Asia/Manila
  # or ansible.builtin.shell: "timedatectl set-timezone Asia/Manila" # use 'UTC' if preferred

- name: Timezone/NTP | Copy timesyncd.conf
  ansible.builtin.copy:
    src: templates/timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: -rw-r--r-- # "0644"
  notify: Timezone/NTP | Restart timesyncd.service

- name: Timezone/NTP | Copy ntp.conf
  ansible.builtin.copy:
    src: templates/ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: -rw-r--r-- # "0644"
  notify: Timezone/NTP | Restart timesyncd.service
