# Configure NTP Timezone Sync
- name: Timezone/NTP | Set local timezone # use 'UTC' maybe? eehhhhhhh
  community.general.timezone:
    name: "{{ timezone }}"
  become: true
  # or ansible.builtin.shell: "timedatectl set-timezone Asia/Manila" # use 'UTC' if preferred

- name: Timezone/NTP (Archlinux) | Copy timesyncd.conf
  ansible.builtin.copy:
    src: templates/timesyncd-arch.conf
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: -rw-r--r-- # "0644"
  become: true
  when: machine_os == 'archlinux'
  notify: Timezone/NTP | Restart timesyncd.service

- name: Timezone/NTP (Archlinux) | Copy ntp.conf
  ansible.builtin.copy:
    src: templates/ntp-arch.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: -rw-r--r-- # "0644"
  become: true
  when: machine_os == 'archlinux'
  notify: Timezone/NTP | Restart timesyncd.service

- name: Timezone/NTP (Debian) | Copy timesyncd.conf
  ansible.builtin.copy:
    src: templates/timesyncd-debian.conf
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: -rw-r--r-- # "0644"
  become: true
  when: machine_os == 'debian'
  notify: Timezone/NTP | Restart timesyncd.service
