# Main Playbook
# run on local: ansible-playbook main.yml --ask-become-pass
# run on remotes: ansible-playbook main.yml --ask-pass --ask-become-pass -i inventory/hosts.ini
# for dry-run (check mode): ansible-playbook --check main.yml --ask-become-pass
# NOTE: playbooks dir are just optional/separate things and are NOT RUN/INCLUDED when running this main playbook

- name: Exquisite Dotfiles Configuration
  hosts: localhost # if have multiple hosts on hosts.ini file then: 'all', 'linux', 'webservers', etc.
  connection: local
  gather_facts: true

  pre_tasks:
    - name: Detect OS and put in machine_os variable
      ansible.builtin.set_fact:
        machine_os: "{{ ansible_facts['os_family'] | lower }}" # can be 'archlinux', 'debian', 'redhat', etc.

    - name: Debug machine_os
      ansible.builtin.debug:
        msg: "The machine is {{ machine_os }}"

    - name: Register Host User
      ansible.builtin.set_fact:
        host_user: "{{ ansible_user_id }}"
      when: host_user is not defined

    - name: Run system_update role
      ansible.builtin.include_role:
        name: system_update

    - name: Configure NTP timesync
      ansible.builtin.include_role:
        name: timezone_ntp

  roles:
    - essentials
    - development # by default installs: go, js/ts, python
    - zsh
    - neovim
    - tmux
    - jetbrains_mono_nerd_font
    # - ssh

    # NOTE: Below are tasks/roles made optional, see group_vars/all.yml
  tasks:
    - name: Optional | Install Java
      ansible.builtin.include_role:
        name: java_role
      when: wants_java # defaults to true

    - name: Optional | Install C#/Dotnet
      ansible.builtin.include_role:
        name: csharp_dotnet_role
      when: wants_csharp_dotnet # defaults to true
