---
- name: gh | detect fedora/redhat
  ansible.builtin.include_tasks: redhat.yml
  when: machine_os == 'redhat'

- name: gh | detect archlinux
  ansible.builtin.include_tasks: archlinux.yml
  when: machine_os == 'archlinux'

- name: gh | detect debian
  ansible.builtin.include_tasks: debian.yml
  when: machine_os == 'debian'
