# sudo dnf install dnf5-plugins
# sudo dnf config-manager addrepo --from-repofile=https://cli.github.com/packages/rpm/gh-cli.repo
# sudo dnf install gh --repo gh-cli
---

- name: gh | install dnf5-plugins
  ansible.builtin.dnf:
    name: dnf5-plugins
    state: present
  become: true

- name: gh | Check if gh-cli repo exists
  ansible.builtin.stat:
    path: /etc/yum.repos.d/gh-cli.repo
  register: gh_cli_repo_stat

- name: gh | Add gh-cli repo
  ansible.builtin.shell: sudo dnf config-manager addrepo --from-repofile=https://cli.github.com/packages/rpm/gh-cli.repo
  when: not gh_cli_repo_stat.stat.exists
  become: true

- name: gh | install github-cli
  ansible.builtin.dnf:
    name: gh
    state: present
    enablerepo: gh-cli
  become: true